name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./android

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup keystore
      run: |
        set -x
        pwd
        ls -la
        touch release.keystore
        echo "dGVzdAo=" | base64 --decode > release.keystore
      working-directory: ./app
    - name: Setup secret properties
      run: |
        touch secret.properties
        echo "keyStore=release.keystore" >> secret.properties
        echo "keyStorePassword=keystorepassword" >> secret.properties
        echo "keyAlias=keyalias" >> secret.properties
        echo "keyAliasPassword=keyaliaspassword" >> secret.properties
        echo "stravaOAuthClientId=client_id" >> secret.properties
        echo "stravaOAuthClientSecret=client_secret" >> secret.properties
      working-directory: ./app
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
