name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup keystore
      run: |
        touch release.keystore
        echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > release.keystore
      working-directory: ./android/app
      env:
        ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
    - name: Setup secret properties
      run: |
        touch secret.properties
        echo "$ANDROID_SECRET_PROPERTIES_BASE64" | base64 --decode > secret.properties
      working-directory: ./android/app
      env:
        ANDROID_SECRET_PROPERTIES_BASE64: ${{ secrets.ANDROID_SECRET_PROPERTIES_BASE64 }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./android
    - name: Build with Gradle
      run: ./gradlew assembleDevRelease
      working-directory: ./android

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        working-directory: ./android/app
        path: build/outputs/apk/**/*.apk
        if-no-files-found: error
